### ISSUE TITLE
Bug: AU PD IG is not autobuilding due to old template

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-pd#44]
The ig.ini currently points to v0.4.0 of the `hl7.au.fhir.template`, which results in a build failure with this error message

```
Template fhir.base.template#0.4.0 names a script, but is not explicit about all ant scripts - this is no longer allowed
```

See failure log from a recently triggered autobuild: https://build.fhir.org/ig/hl7au/au-fhir-pd/branches/master/failure/build.log

[au-fhir-base](https://github.com/hl7au/au-fhir-base/blob/master/ig.ini#L3) and [au-fhir-core](https://github.com/hl7au/au-fhir-core/blob/master/ig.ini#L3) both recently updated their ig.ini files to point to v0.6.0 of the template, for the same issue.

Therefore, update the au-fhir-pd ig.ini to point to 0.6.0 of the template

**Comment by robeastwood-agency** [comment]
Planning to submit a PR for this over the next day, unless it's addressed in the meantime

**Comment by brettesler-ext** [comment]
Hi Rob - I'll just update now

**Comment by brettesler-ext** [comment]
Fixed and rebuilt now: https://github.com/hl7au/au-fhir-pd/commit/fe6e5f2ee714e7b879987931e311c774543c0e90

**Comment by robeastwood-agency** [comment]
Thanks very much @brettesler-ext
